# Profile information
name: The history of Chinese minorities
title: The history of Chinese minorities
description: > # this means to ignoire newlines until "baseurl:"
  The discription of Chinese minorities history.
permalink: ':title/'
baseurl: "/The history of Chinese minorities" # the subpath of your site, e.g. /blog
url: "artemsheludko.pw" # the base hostname & protocol for your site, e.g. http://example.com

# Social
facebook: #Add your Facebook
twitter: #Add your Twitter
google-plus: #Add your Google+
github: #Add your Github

# Contact form
email: #your-email@domain.com

# Comments
discus-identifier: # Add your Disqus identifier

# Paginate
paginate: 5
paginate_path: /page:num/

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
include: [_pages]